name: Scheduled Demo

on:
  workflow_dispatch:       # allows manual run
  schedule:
    - cron: '*/1 * * * *'  # every 1 minute (may delay a bit)

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Print UTC time
        run: |
          echo "Current UTC time:"
          date -u
