name: Scheduled Demo

on:
  schedule:
    - cron: '*/5 * * * *'  # runs every 5 minutes
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Print time
        run: echo "Current UTC time $(date -u)"
